apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks-node
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
      env:
      - "REACT_APP_DOMAIN_API_REST=https://api"
